# Generated by Django 5.2.15 on 2026-06-25 13:43

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_lesson_slug_section_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
