# Generated by Django 5.2.15 on 2026-06-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL of the video (e.g. YouTube, Vimeo, etc.)', max_length=500, null=True),
        ),
    ]
