# Generated by Django 5.2.15 on 2026-06-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_lesson_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('badge_text', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='banners/images/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of the banner in the list')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this banner should be active and shown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
